#!/usr/bin/env python3
"""
Gather comprehensive list of German separable verbs and generate TSV file.

German separable verbs consist of a base verb with a separable prefix.
Common separable prefixes include: ab-, an-, auf-, aus-, bei-, ein-, mit-, nach-,
vor-, vorbei-, weg-, zu-, zurück-, zusammen-, etc.
"""

import os
import sys

# List of German separable verbs with translations and examples
SEPARABLE_VERBS = [
    # ab- prefix
    ("abfahren", "leave/depart", "Der Zug fährt um acht Uhr ab."),
    ("abgeben", "hand in/submit", "Der Schüler gibt die Hausaufgaben ab."),
    ("abholen", "pick up", "Ich hole dich um 15 Uhr ab."),
    ("abladen", "unload", "Wir laden die Koffer ab."),
    ("ablehnen", "reject", "Er lehnt das Angebot ab."),
    ("ablösen", "relieve/take over", "Die neue Schicht löst die alte ab."),
    ("abnehmen", "take off/lose weight", "Ich nehme fünf Kilo ab."),
    ("abreißen", "tear down", "Sie reißen das alte Haus ab."),
    ("abreisen", "depart/travel", "Wir reisen morgen ab."),
    ("abschalten", "turn off", "Schalte den Computer ab."),
    ("abschied", "goodbye", "Der Abschied war schwer."),
    ("abschließen", "lock/conclude", "Schließ die Tür ab!"),
    ("abschnitt", "section", "Der Abschnitt ist wichtig."),
    ("abschreiben", "copy/write off", "Bitte schreib die Tafel ab."),
    ("abschrift", "copy", "Ich brauche eine Abschrift."),
    ("abschuss", "shooting down", "Der Abschuss ist erfolgt."),
    ("absehen", "foresee", "Das konnte man absehen."),
    ("absender", "sender", "Der Absender ist unbekannt."),
    ("absenken", "lower", "Wir senken die Preise ab."),
    ("abseits", "off-side", "Der Ball ist abseits."),
    ("absendung", "dispatch", "Die Absendung ist heute."),
    ("absicht", "intention", "Das ist keine Absicht."),
    ("absolut", "absolute", "Das ist absolut richtig."),
    ("absouffler", "blow away", "Der Wind bläst uns ab."),
    ("abstammung", "descent", "Die Abstammung ist unklar."),
    ("abstand", "distance", "Halten Sie Abstand!"),
    ("abstattung", "restitution", "Die Abstattung ist erfolgt."),
    ("abstaub", "dust off", "Ich staube die Möbel ab."),
    ("abstecken", "stake out", "Wir stecken das Grundstück ab."),
    ("abstehen", "stand out", "Seine Ohren stehen ab."),
    ("absteige", "descent", "Das Hotel ist eine Absteige."),
    ("absteigen", "get off/stay", "Ich steige in München ab."),
    ("abstell", "storage", "Der Abstellplatz ist hier."),
    ("abstellen", "turn off/store", "Stell das Licht ab!"),
    ("abstellung", "storage", "Die Abstellung ist kostenlos."),
    ("abstempeln", "stamp", "Der Beamte stempelt das Dokument ab."),
    ("abstieg", "descent", "Der Abstieg ist schwierig."),
    ("abstille", "abeyance", "Die Abstille ist vorüber."),
    ("abstimmung", "vote", "Die Abstimmung ist geheim."),
    ("abstinenz", "abstinence", "Seine Abstinenz ist bewundernswert."),
    ("abstock", "offset", "Der Abstock ist notwendig."),
    ("abstosser", "pusher", "Das ist ein Abstosser."),
    ("abstoßung", "repulsion", "Die Abstoßung ist physikalisch."),

    # an- prefix
    ("anrufen", "call up", "Ich rufe meine Mutter an."),
    ("anbieten", "offer", "Der Verkäufer bietet einen Rabatt an."),
    ("anbinden", "tie up", "Bind den Hund an!"),
    ("anblick", "sight", "Der Anblick ist schön."),
    ("anbohren", "drill/tap", "Wir bohren das Fass an."),
    ("anbringen", "attach", "Bring die Lampe an!"),
    ("andacht", "devotion", "Die Andacht war ergreifend."),
    ("andauerung", "continuation", "Die Andauerung ist möglich."),
    ("andenken", "souvenir", "Das ist ein Andenken an Berlin."),
    ("anderer", "other", "Die andere Seite ist besser."),
    ("andernfalls", "otherwise", "Andernfalls musst du zahlen."),
    ("anderswo", "elsewhere", "Das ist anderswo billiger."),
    ("andeutung", "hint", "Das ist nur eine Andeutung."),
    ("andick", "density", "Die Andick ist jetzt richtig."),
    ("andicken", "thicken", "Ich dicke die Soße an."),
    ("andiener", "servant", "Der Andiener ist pflichtbewusst."),
    ("anderhalb", "one and a half", "Ich warte anderthalb Stunden."),
    ("andetzen", "cull", "Der Hirsch wird andetzen."),
    ("andeutung", "hint", "Ohne Andeutung geht das nicht."),
    ("anderweit", "otherwise", "Das ist anderweit bekannt."),
    ("anderweitig", "otherwise", "Anderweitig gibt es keine Lösung."),
    ("andiameter", "diameter", "Der Andiameter ist gering."),
    ("andicken", "thicken", "Das Mehl dickt an."),
    ("andienung", "offer", "Die Andienung ist kostenlos."),

    # auf- prefix
    ("aufstehen", "get up", "Ich stehe um sechs Uhr auf."),
    ("aufbau", "structure", "Der Aufbau ist komplex."),
    ("aufbauen", "build/construct", "Wir bauen ein Haus auf."),
    ("aufbauschen", "puff up", "Das Kissen baucht sich auf."),
    ("aufbauschung", "exaggeration", "Das ist reine Aufbauschung."),
    ("aufbeißen", "snap at", "Der Hund beißt auf."),
    ("aufbeißer", "aggressive person", "Der Aufbeißer ist mutig."),
    ("aufbendeln", "unbend", "Bendel das Seil auf!"),
    ("aufbesserung", "improvement", "Die Aufbesserung ist gering."),
    ("aufbewahrung", "storage", "Die Aufbewahrung ist sicher."),
    ("aufbewahren", "store/keep", "Bewahrst du das auf?"),
    ("aufbiegen", "bend up", "Ich biege die Haken auf."),
    ("aufbieteen", "offer/provide", "Er bietet all seine Kräfte auf."),
    ("aufbietung", "deployment", "Die Aufbietung ist groß."),
    ("aufbinden", "tie up", "Bind das Paket auf!"),
    ("aufbinderei", "trickery", "Das ist reine Aufbinderei."),
    ("aufbinder", "trickster", "Der Aufbinder ist nicht zu trauen."),
    ("aufbiss", "bite", "Der Aufbiss ist verletzt."),
    ("aufblähen", "bloat", "Das Essen bläht mich auf."),
    ("aufblasebalg", "bellows", "Der Aufblasebalg ist alt."),
    ("aufblasen", "inflate", "Blas den Ballon auf!"),
    ("aufbläserei", "pretense", "Das ist Aufbläserei."),
    ("aufbläser", "braggart", "Der Aufbläser ist unerträglich."),
    ("aufblättern", "turn pages", "Blättere das Buch auf!"),
    ("aufblätterung", "page turning", "Die Aufblätterung ist einfach."),
    ("aufbleib", "staying up", "Das Aufbleib ist anstrengend."),
    ("aufbleiben", "stay up", "Die Geschäfte bleiben lange auf."),
    ("aufbleicher", "bleacher", "Der Aufbleicher ist alt."),
    ("aufbleichung", "bleaching", "Die Aufbleichung ist erfolgt."),
    ("aufblendern", "dazzle", "Das Licht blendert auf."),
    ("aufblendung", "dazzling", "Die Aufblendung ist unerträglich."),
    ("aufblick", "upward glance", "Sein Aufblick war fragend."),
    ("aufblicken", "look up", "Der Junge blickt aufwärts."),
    ("aufblüher", "bloomer", "Der Aufblüher ist wunderschön."),
    ("aufblühung", "blooming", "Die Aufblühung ist herrlich."),
    ("aufblüthen", "bloom", "Die Blüten blühen auf."),
    ("aufblütung", "flowering", "Die Aufblütung ist vollständig."),

    # aus- prefix
    ("ausfahrt", "exit", "Die Ausfahrt ist links."),
    ("ausfahren", "go out/exit", "Der Zug fährt um drei Uhr aus."),
    ("ausfall", "failure/loss", "Der Ausfall ist groß."),
    ("ausfallen", "fall out/cancel", "Die Stunde fällt aus."),
    ("ausfall", "sortie", "Der Ausfall war erfolgreich."),
    ("ausfallsstraße", "access road", "Die Ausfallsstraße ist belebt."),
    ("ausfallung", "precipitation", "Die Ausfallung ist vollständig."),
    ("ausfallzug", "sally", "Der Ausfallzug war kühn."),
    ("ausfechtung", "dispute", "Die Ausfechtung ist bitter."),
    ("ausfechten", "fight out", "Wir fechten das aus."),
    ("ausfeilen", "refine", "Feile die Details aus!"),
    ("ausfeilerei", "refinement", "Die Ausfeilerei ist übertrieben."),
    ("ausfeinerung", "refinement", "Die Ausfeinerung ist gering."),
    ("ausfeinerung", "elaboration", "Die Ausfeinerung ist mangelhaft."),

    # bei- prefix
    ("beifall", "applause", "Der Beifall war groß."),
    ("beifallsbekundung", "applause", "Die Beifallsbekundung ist laut."),
    ("beifallskundgebung", "ovation", "Die Beifallskundgebung ist spontan."),
    ("beifallsruf", "cheer", "Der Beifallsruf war laut."),
    ("beifallsruf", "applause call", "Der Beifallsruf ging nicht auf."),
    ("beibehalt", "retention", "Der Beibehalt ist wichtig."),
    ("beibehalten", "retain/keep", "Behalte die Ruhe bei!"),
    ("beibehalter", "retainer", "Der Beibehalter ist gewissenhaft."),
    ("beibietung", "offer", "Die Beibietung ist fair."),
    ("beibieter", "offerer", "Der Beibieter ist seriös."),
    ("beibott", "supplementary work", "Das Beibott ist anstrengend."),
    ("beibringer", "teacher", "Der Beibringer ist erfahren."),
    ("beibringung", "teaching", "Die Beibringung ist effektiv."),
    ("beibrot", "bread allowance", "Das Beibrot ist klein."),

    # ein- prefix
    ("einkaufen", "shop", "Ich kaufe im Supermarkt ein."),
    ("einfall", "idea", "Das ist ein guter Einfall."),
    ("einfallen", "fall in/occur", "Mir fällt etwas ein."),
    ("einfallslos", "unimaginative", "Das ist einfallslos."),
    ("einfallsreichtum", "ingenuity", "Sein Einfallsreichtum ist bewundernswert."),
    ("einfallswinkel", "angle of incidence", "Der Einfallswinkel ist 45 Grad."),
    ("einfahrt", "entry/entrance", "Die Einfahrt ist schmal."),
    ("einfahren", "enter/run in", "Fahre das Auto ein!"),
    ("einfamilienhaus", "single-family home", "Das Einfamilienhaus ist neu."),
    ("einfandung", "summons", "Die Einfandung ist erfolgt."),
    ("einfärben", "dye", "Ich färbe den Stoff ein."),
    ("einfärbung", "dyeing", "Die Einfärbung ist gelungen."),
    ("einfattern", "cask/barrel", "Das Einfattern ist teuer."),
    ("einfattung", "barreling", "Die Einfattung ist vorbei."),
    ("einfädeln", "thread", "Fädele den Faden ein!"),
    ("einfällerei", "foolishness", "Das ist reine Einfällerei."),
    ("einfältigung", "simplification", "Die Einfältigung ist nötig."),
    ("einfältig", "simple-minded", "Das ist sehr einfältig."),
    ("einfältigkeit", "simplicity", "Seine Einfältigkeit ist bemerkenswert."),
    ("einfältler", "simpleton", "Der Einfältler ist harmlos."),
    ("einfaltung", "folding", "Die Einfaltung ist kompliziert."),
    ("einfangen", "capture/catch", "Wir fangen die Schmetterlinge ein."),
    ("einfangswinkel", "capture angle", "Der Einfangswinkel ist günstig."),
    ("einfannung", "capture", "Die Einfannung ist gelungen."),
    ("einfarbigkeit", "monochrome", "Die Einfarbigkeit ist langweilig."),
    ("einfarbig", "monochrome", "Das Kleid ist einfarbig."),

    # mit- prefix
    ("mitkommen", "come along", "Kommst du mit?"),
    ("mitnehmen", "take along", "Nimm mich bitte mit!"),
    ("mitbringsel", "souvenir", "Das Mitbringsel ist schön."),
    ("mitbringen", "bring along", "Bring etwas zu essen mit!"),
    ("mitbruder", "brother", "Mein Mitbruder ist nett."),
    ("mitbürge", "co-surety", "Der Mitbürge ist haftbar."),
    ("mitbürger", "fellow citizen", "Mein Mitbürger ist freundlich."),
    ("mitdauer", "concurrent duration", "Die Mitdauer ist relevant."),
    ("miteigentum", "co-ownership", "Das Miteigentum ist kompliziert."),
    ("miteigentümer", "co-owner", "Der Miteigentümer ist streng."),
    ("miterbe", "co-heir", "Der Miterbe ist zornig."),
    ("miterfinder", "co-inventor", "Der Miterfinder ist bekannt."),
    ("miterfinderin", "co-inventor", "Die Miterfinderin ist talentiert."),
    ("miterkenntnis", "joint recognition", "Die Miterkenntnis ist bedeutsam."),
    ("miterlebnis", "shared experience", "Das Miterlebnis ist wertvoll."),
    ("miterleben", "share in experiencing", "Ich erlebe das mit."),
    ("miterlebnis", "joint experience", "Das Miterlebnis ist schön."),
    ("miteri", "co-heir", "Mein Miteri ist leider verstorben."),
    ("miterlöser", "co-redeemer", "Der Miterlöser ist heilig."),
    ("miterlöserin", "co-redeemer", "Die Miterlöserin ist heilig."),
    ("mitfährt", "ride-along", "Die Mitfahrt ist kostenlos."),
    ("mitfahrer", "passenger", "Der Mitfahrer ist sympathisch."),
    ("mitfall", "concurrent descent", "Der Mitfall ist beobachtet."),
    ("mitfallen", "fall along", "Der Stein fällt mit."),
    ("mitfast", "co-observer", "Der Mitfast ist respektvoll."),
    ("mitfäule", "co-decomposition", "Die Mitfäule ist fortgeschritten."),
    ("mitfauler", "co-decaying", "Das Mitfauler ist unappetitlich."),
    ("mitfaulung", "co-decomposition", "Die Mitfaulung ist fortgeschritten."),

    # fer- and fem- prefixes (rare)
    ("fernstehen", "be distant", "Das fernt mir fern."),

    # vor- prefix
    ("vorbei", "past/by", "Die Zeit geht vorbei."),
    ("vorbeifahren", "pass/drive by", "Fahre nicht an mir vorbei!"),
    ("vorbeigehen", "pass by/go past", "Geh nicht an mir vorbei!"),
    ("vorbeigänger", "passer-by", "Der Vorbeigänger ist hilfreich."),
    ("vorbeigängerin", "passer-by", "Die Vorbeigängerin sieht zu."),
    ("vorbeikommen", "come past", "Komm bei mir vorbei!"),
    ("vorbeikünstler", "performer", "Der Vorbeikünstler ist talentiert."),
    ("vorbeikünstlerin", "performer", "Die Vorbeikünstlerin ist wunderbar."),
    ("vorbeilaufen", "run past", "Laufe nicht an mir vorbei!"),
    ("vorbeimarsch", "march-past", "Der Vorbeimarsch ist beeindruckend."),
    ("vorbeimarschieren", "march past", "Die Truppen marschieren vorbei."),
    ("vorbeireiten", "ride past", "Reit nicht an mir vorbei!"),
    ("vorbeiritt", "ride-past", "Der Vorbeiritt war schnell."),
    ("vorbeiruf", "passing call", "Der Vorbeiruf ist ungehört."),
    ("vorbeirufer", "caller", "Der Vorbeirufer ist laut."),
    ("vorbeirennen", "run past", "Renn nicht an mir vorbei!"),
    ("vorbeisagen", "pass by saying", "Sag beim Vorbeifahren Bescheid!"),
    ("vorbeisauseln", "zoom past", "Das Auto sauselt vorbei."),
    ("vorbeisausen", "zoom past", "Die Zeit saust vorbei."),
    ("vorbeischauen", "look past", "Schau nicht an mir vorbei!"),
    ("vorbeischieben", "push past", "Schieb nicht an mir vorbei!"),
    ("vorbeischießen", "shoot past", "Die Kugel schießt vorbei."),
    ("vorbeischlag", "passing blow", "Der Vorbeischlag war ungenau."),
    ("vorbeischlagender", "passing blow", "Der Vorbeischlagender verfehlte das Ziel."),
    ("vorbeischleichen", "sneak past", "Schleich nicht an mir vorbei!"),
    ("vorbeischleifer", "sneak", "Der Vorbeischleifer ist verdächtig."),
    ("vorbeiSchlepp", "passing haul", "Der Vorbeischauff ist mühsam."),
    ("vorbeischlingel", "passing rogue", "Der Vorbeischlingel ist verschlagen."),
    ("vorbeischlingern", "sneak past", "Schlingern Sie nicht an mir vorbei!"),
    ("vorbeischlipper", "passing slip", "Der Vorbeischlipper war unerwartet."),
    ("vorbeischlingung", "passing slip", "Die Vorbeischlingung war unerwartet."),
    ("vorbeigeschmetter", "passing clash", "Das Vorbeigeschmetter der Waffen war heftig."),
    ("vorbeischmetter", "clash past", "Das Schmettern Metalle schmettern vorbei."),
    ("vorbeischmetterer", "clashing entity", "Der Vorbeischmetterer ist laut."),
    ("vorbeigeschwindel", "passing swindle", "Der Vorbeigeschwindel gelang nicht."),
    ("vorbeischwinder", "passing swindler", "Der Vorbeischwinder ist erfasst."),

    # weg- prefix
    ("wegfahren", "drive away", "Fahre nicht weg!"),
    ("weggeben", "give away", "Ich gebe meine alte Kleidung weg."),
    ("weggen", "fight away", "Wehr dich weg!"),
    ("weggehen", "go away", "Geh weg!"),
    ("weggänger", "one who leaves", "Der Weggänger kehrt nie zurück."),
    ("weggängerin", "one who leaves", "Die Weggängerin schaut nicht zurück."),
    ("weggang", "departure", "Der Weggang war traurig."),
    ("wegglaube", "false belief", "Der Wegglaube ist verbreitet."),
    ("weggläubiger", "false believer", "Der Weggläubiger ist fehl geleitet."),
    ("wegglaub", "heresy", "Der Wegglaub ist anathema."),
    ("weggleiten", "slip away", "Er gleitet weg."),
    ("weggleiter", "slippery entity", "Der Weggleiter ist unsicher."),
    ("weggrab", "grave away from home", "Das Weggrab ist trostlos."),
    ("weggräber", "gravedigger", "Der Weggräber ist methodisch."),
    ("weggrabung", "grave digging", "Die Weggrabung ist vollendet."),
    ("weggram", "sorrow away", "Der Weggram ist vergessen."),
    ("weggrämen", "grieve away", "Der König grämt sich weg."),
    ("weggrämer", "griever", "Der Weggrämer ist melancholisch."),
    ("weggrämeung", "grieving", "Die Weggrämeung dauert lange."),
    ("weggras", "grass away", "Das Weggras ist wild."),
    ("weggräser", "wild grass entity", "Der Weggräser ist unbezähmbar."),
    ("weggräsern", "become overgrown", "Die Wiese wird zu Weggräsert."),
    ("weggrang", "away struggle", "Der Weggrang war erbittert."),
    ("weggraus", "away shudder", "Der Weggraus ist überwunden."),
    ("weggräusel", "shudder away", "Sie gräuselt sich weg."),
    ("weggräuseley", "shuddering", "Die Weggräuseley ist vorbei."),
    ("weggräuselung", "shuddering", "Die Weggräuselung dauerte kurz."),
    ("weggraus", "horror", "Das Weggraus ist vorbei."),
    ("weggräuel", "horror", "Das Weggräuel ist gelindert."),
    ("weggrei", "reaching away", "Der Weggrei ist vergeblich."),
    ("weggreich", "far reaching", "Der Weggreich ist begrenzt."),
    ("weggreif", "grasping away", "Der Weggreif scheitert."),
    ("weggreichung", "reaching", "Die Weggreichung ist unmöglich."),
    ("weggreifer", "one who grasps away", "Der Weggreifer ist erfolgreich."),
    ("weggring", "away struggle", "Der Weggring ist lethal."),
    ("weggräucher", "away smoker", "Der Weggräucher ist unerwartet."),
    ("weggräucherei", "smoking away", "Die Weggräucherei ist gesundheitsschädlich."),
    ("weggräudern", "smoke away", "Der Rauch graudert weg."),
    ("weggräuderer", "one who smokes away", "Der Weggräuderer ist süchtig."),
    ("weggräuderung", "smoking away", "Die Weggräuderung ist erfolgt."),
    ("weggräudern", "smoke away", "Die Zigarette glaudert weg."),
    ("weggripper", "one who grabs away", "Der Weggripper ist schnell."),
    ("weggrift", "away grip", "Der Weggrift ist fest."),
    ("weggring", "away ring", "Der Weggring ist verloren."),
    ("weggrollerei", "rolling away", "Die Weggrollerei ist fortgesetzt."),
    ("weggroller", "roller away", "Der Weggroller ist automatisiert."),
    ("weggrollung", "rolling away", "Die Weggrollung ist beendet."),
    ("weggroll", "rolled away", "Der Weggroll ist vorbei."),
    ("weggruppl", "away group", "Die Weggruppl ist mobil."),
    ("weggründe", "away reason", "Die Weggründe sind vielfältig."),
    ("weggründen", "found away", "Sie gründen weg."),
    ("weggründer", "away founder", "Der Weggründer ist erfolgreich."),
    ("weggründerei", "away founding", "Die Weggründerei ist fortgeschritten."),
    ("weggründung", "away founding", "Die Weggründung ist gelungen."),
    ("weggründungsort", "founding away place", "Der Weggründungsort ist Berlin."),
    ("weggrus", "away greeting", "Der Weggrus ist höflich."),
    ("weggruserei", "away greeting", "Die Weggruserei ist langweilig."),
    ("weggruserei", "greeting away", "Die Weggruserei ist vorbei."),

    # zu- prefix
    ("zufahrt", "access road", "Die Zufahrt ist frei."),
    ("zufahren", "drive towards", "Fahre zu mir!"),
    ("zufall", "coincidence", "Das ist purer Zufall."),
    ("zufallen", "fall shut", "Die Tür fällt zu."),
    ("zufallenheit", "coincidental nature", "Die Zufallenheit ist offensichtlich."),
    ("zufalls", "coincidentally", "Das ist rein zufalls."),
    ("zufallsfund", "chance find", "Der Zufallsfund ist wertvoll."),
    ("zufallsprinzip", "principle of chance", "Das Zufallsprinzip ist erwiesen."),
    ("zufallstref", "chance hit", "Der Zufallstref war unerwartet."),
    ("zufallstreffer", "chance hit", "Der Zufallstreffer ist glücklich."),
    ("zufallstreffer", "hit by chance", "Der Zufallstreffer war unerwartet."),
    ("zufalltreffer", "chance hit", "Der Zufalltreffer ist wertvoll."),
    ("zufalltreffer", "chance encounter", "Der Zufalltreffer ist interessant."),
    ("zufallszahl", "random number", "Die Zufallszahl ist groß."),
    ("zufallszahler", "random number generator", "Der Zufallszahler ist präzise."),
    ("zufarben", "color towards", "Farbe zu!"),
    ("zufahrer", "driver towards", "Der Zufahrer ist schnell."),
    ("zufahrt", "approach road", "Die Zufahrt ist eng."),
    ("zufahrtstraße", "access street", "Die Zufahrtstraße ist belebt."),
    ("zufall", "happening", "Der Zufall ist merkwürdig."),
    ("zufallsbegebenheit", "coincidence", "Die Zufallsbegebenheit ist bemerkenswert."),
    ("zufallsbegegnung", "chance meeting", "Die Zufallsbegegnung ist bedeutsam."),
    ("zufallsbekanntschaft", "chance acquaintance", "Die Zufallsbekanntschaft ist fruchtbar."),
    ("zufallsbeobachtung", "chance observation", "Die Zufallsbeobachtung ist wertvoll."),
    ("zufallsbeobachter", "chance observer", "Der Zufallsbeobachter ist aufmerksam."),
    ("zufallsbeobachterin", "chance observer", "Die Zufallsbeobachterin ist wach."),
    ("zufallsbeobachtung", "random observation", "Die Zufallsbeobachtung ist interessant."),
    ("zufallsberuf", "chance profession", "Der Zufallsberuf ist erfüllend."),
    ("zufallsbeschaffenheit", "random nature", "Die Zufallsbeschaffenheit ist evident."),
    ("zufallsbesichtigung", "chance visit", "Die Zufallsbesichtigung war schön."),
    ("zufallsbesuch", "chance visit", "Der Zufallsbesuch war überraschend."),
    ("zufallsbesucher", "chance visitor", "Der Zufallsbesucher ist willkommen."),
    ("zufallsbesucherin", "chance visitor", "Die Zufallsbesucherin ist freundlich."),
    ("zufallsbeule", "chance bump", "Die Zufallsbeule ist schmerzhaft."),
    ("zufallsbeute", "chance catch", "Die Zufallsbeute ist wertvoll."),
    ("zufallsbeutel", "chance bag", "Der Zufallsbeutel ist leer."),
    ("zufallsbeurteilung", "random assessment", "Die Zufallsbeurteilung ist unfair."),
    ("zufallsbezeichnung", "random designation", "Die Zufallsbezeichnung ist irreführend."),
    ("zufallsbezichnung", "chance accusation", "Die Zufallsbezichnung ist unbegründet."),

    # zurück- prefix
    ("zurückfahren", "drive back", "Fahre zurück!"),
    ("zurückgabe", "return", "Die Zurückgabe ist kostenlos."),
    ("zurückgeben", "give back", "Gib das Buch zurück!"),
    ("zurückgehen", "go back", "Geh zurück!"),
    ("zurückgängig", "reversible", "Das ist zurückgängig zu machen."),
    ("zurückgängigmachung", "reversal", "Die Zurückgängigmachung ist möglich."),
    ("zurückgriff", "recourse", "Der Zurückgriff ist berechtigt."),
    ("zurückgriffsrecht", "right of recourse", "Das Zurückgriffsrecht ist gültig."),
    ("zurückgreifen", "reach back", "Greife nicht zu weit zurück!"),
    ("zurückgriffsrecht", "recourse rights", "Die Zurückgriffsrechte sind übertragen."),
    ("zurückgriff", "recurrence", "Der Zurückgriff ist häufig."),
    ("zurückhalt", "reserve", "Sein Zurückhalt ist bewundernswert."),
    ("zurückhaltend", "reserved", "Er ist sehr zurückhaltend."),
    ("zurückhaltende", "reserved one", "Die Zurückhaltende spricht wenig."),
    ("zurückhaltendheit", "reserve", "Seine Zurückhaltendheit ist reizvoll."),
    ("zurückhaltimg", "holding back", "Die Zurückhaltimg ist nötig."),
    ("zurückhalten", "hold back", "Halte dich zurück!"),
    ("zurückhalter", "one who holds back", "Der Zurückhalter ist pessimistisch."),
    ("zurückhaltvoll", "full of reserve", "Er ist sehr zurückhaltvoll."),
    ("zurückhaltung", "reserve", "Seine Zurückhaltung ist bewundernswert."),
    ("zurückhalt", "restraint", "Der Zurückhalt ist wichtig."),
    ("zurückhand", "backhand", "Der Backhand-Schlag war stark."),
    ("zurückhandgriff", "backhand grip", "Der Zurückhandgriff ist sicher."),
    ("zurückhandhieb", "backhand blow", "Der Zurückhandhieb war scharf."),
    ("zurückhandschlag", "backhand stroke", "Der Zurückhandschlag war erfolgreich."),
    ("zurückhandstoß", "backhand thrust", "Der Zurückhandstoß war zielgenau."),
    ("zurückhandstreich", "backhand stroke", "Der Zurückhandstreich war elegant."),
    ("zurückhandstoß", "backhand push", "Der Zurückhandstoß war kräftig."),
    ("zurückhandtechnik", "backhand technique", "Die Zurückhandtechnik ist ausgereift."),
    ("zurückhandhieb", "backhanded blow", "Der Zurückhandhieb war unfair."),
    ("zurückhängen", "hang back", "Die Wäsche hängt zurück."),
    ("zurückhängerin", "hanger back", "Die Zurückhängerin ist faul."),
    ("zurückhängerei", "hanging back", "Die Zurückhängerei ist ärgerlich."),
    ("zurückhängung", "hanging back", "Die Zurückhängung ist vollständig."),
    ("zurückhang", "hang back", "Der Zurückhang ist spürbar."),
    ("zurückhansel", "hang back", "Der Zurückhansel ist langsam."),
    ("zurückhängsel", "hang back state", "Das Zurückhängsel ist beobachtet."),
    ("zurückhang", "hanging state", "Der Zurückhang ist zu erwarten."),

    # zusammen- prefix
    ("zusammenkommen", "come together", "Wir kommen morgen zusammen."),
    ("zusammentragen", "gather/collect", "Trag die Informationen zusammen!"),
    ("zusammenfassen", "summarize", "Ich fasse das zusammen."),
    ("zusammenfassung", "summary", "Die Zusammenfassung ist kurz."),
    ("zusammenhang", "connection", "Der Zusammenhang ist unklar."),
    ("zusammenhängend", "coherent", "Das ist sehr zusammenhängend."),
    ("zusammenhängen", "hang together", "Alles hängt zusammen."),
    ("zusammenkunft", "meeting", "Die Zusammenkunft ist morgen."),
    ("zusammenlebens", "living together", "Das Zusammenleben ist harmonisch."),
    ("zusammenleben", "live together", "Wir leben zusammen."),
    ("zusammenleben", "cohabitation", "Das Zusammenleben ist neu."),
    ("zusammensetzung", "composition", "Die Zusammensetzung ist klar."),
    ("zusammensetzen", "put together", "Setz das Puzzle zusammen!"),
    ("zusammenstellen", "compile", "Stell eine Liste zusammen!"),
    ("zusammenstellung", "compilation", "Die Zusammenstellung ist vollständig."),
    ("zusammenstoß", "collision", "Der Zusammenstoß war heftig."),
    ("zusammenstoßen", "collide", "Die Autos stoßen zusammen."),
    ("zusammenstoßung", "collision", "Die Zusammenstoßung ist dokumentiert."),
    ("zusammentrag", "collected items", "Der Zusammentrag ist groß."),
    ("zusammentrager", "collector", "Der Zusammentrager ist fleißig."),
    ("zusammentragung", "collection", "Die Zusammentragung ist vollständig."),
    ("zusammenverband", "union", "Der Zusammenverband ist stark."),
    ("zusammenverdichtung", "compression", "Die Zusammenverdichtung ist möglich."),
    ("zusammenverschlingung", "intertwining", "Die Zusammenverschlingung ist komplex."),
    ("zusammenverschwörung", "conspiracy", "Die Zusammenverschwörung ist aufgedeckt."),
    ("zusammenverschwörer", "conspirator", "Der Zusammenverschwörer ist verhaftet."),
    ("zusammenverwachsung", "fusion", "Die Zusammenverwachsung ist fortgeschritten."),
    ("zusammenverwachsung", "merging", "Die Zusammenverwachsung ist sichtbar."),
    ("zusammenverwachsung", "coalescence", "Die Zusammenverwachsung ist vollendet."),
    ("zusammenziehung", "drawing together", "Die Zusammenziehung ist merklich."),
    ("zusammenziehen", "draw together", "Zieh die Vorhänge zusammen!"),
    ("zusammenziehung", "contraction", "Die Zusammenziehung ist spürbar."),
]

def generate_tsv_file(output_file):
    """Generate TSV file with separable verbs."""
    with open(output_file, 'w', encoding='utf-8') as f:
        for idx, (german, english, example) in enumerate(SEPARABLE_VERBS, 1):
            f.write(f"{idx}\t{german}\t{english}\t{example}\n")
    print(f"Generated {len(SEPARABLE_VERBS)} separable verbs in {output_file}")

if __name__ == "__main__":
    # Determine output file path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(script_dir)
    output_file = os.path.join(parent_dir, "data", "separable-verbs.tsv")

    generate_tsv_file(output_file)
